apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "eurek8s-controller.fullname" . }}-leader-election-role
  labels:
    {{- include "eurek8s-controller.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eurek8s-controller.fullname" . }}-leader-election-rolebinding
  labels:
    {{- include "eurek8s-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "eurek8s-controller.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "eurek8s-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
