kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "eurek8s-controller.fullname" . }}-cluster-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eurek8s-controller.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "extensions","networking.k8s.io" ]
    resources: [ "ingresses" ]
    verbs: [ 'list', 'get', 'watch' ]
  - apiGroups: [ 'discovery.eurek8s.com' ]
    resources: [ 'eurekaapplications' ]
    verbs: [ '*' ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "eurek8s-controller.fullname" . }}-cluster-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eurek8s-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "eurek8s-controller.fullname" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "eurek8s-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
